from src.common.enums.FieldStatus import FieldStatus

WIDTH, HEIGHT = 800, 800
WINDOW_BORDER = 4
BOARD_BORDER = 2

BOARD_SIZE = 8
BOARD_FIELD_WIDTH = (WIDTH - WINDOW_BORDER) // BOARD_SIZE
BOARD_FIELD_HEIGHT = (HEIGHT - WINDOW_BORDER) // BOARD_SIZE

WHITE = (255, 255, 255)
RED = (196, 0, 0)

BOARD_0_FIELD_COLOR = (196, 196, 196)
BOARD_1_FIELD_COLOR = (183, 183, 183)
BOARD_FIELD_BORDER_COLOR = (157, 157, 157)

PLAYER_1_FIELD_STATUSES = [FieldStatus.PLAYER_1_REGULAR_PAWN, FieldStatus.PLAYER_1_KING]
PLAYER_2_FIELD_STATUSES = [FieldStatus.PLAYER_2_REGULAR_PAWN, FieldStatus.PLAYER_2_KING]
